---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git
    apt:
     name: git
     state: present 

  - name: i want install webserver
    apt:
     name: apache2
     state: present

  - name: i want to start mywebserver
    service:
      name: apache2
      state: started
      