---
- hosts: all
  become: yes
  tasks: 
   - name: i want to install webserver on ubuntu node
     apt: 
      name: apache2
      state: present
     when: ansible_os_family =="Debian" 
   - name: i want to start webserver on ubuntu node
     service: 
      name: apache2 
      state: started
     when: ansible_os_family =="Debian"
 
   - name: i want to install webserver on RedHat node
     yum:
      name: httpd
      state: present 
     when: ansible_os_family =="RedHat"  
   - name: i want start webserveron on RedHat 
     service: 
      name: httpd
      state: started 
     when: ansible_os_family =="*family*"
